spring:
  profiles:
    active: dev
server:
  port: ${PORT:8081}
---
spring:
  profiles: dev
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
---
spring:
  profiles: standalone
eureka:
  client:
    enabled: false
---
spring:
  profiles: cloud
  cloud:
    config:
      uri: ${vcap.services.${PREFIX:}configserver.credentials.uri:http://localhost:8888}